apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-znei
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tqiw-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-znei@sha256:6f57639ba14f6262be7a975e8caa176c7b5593ff3f030d931d8bb4334d3d278c
        name: my-python
        resources: {}
status: {}
